name: wechat
description: A new Flutter application.


dependencies:
  flutter:
    sdk: flutter

  flutter_webview_plugin: "^0.2.1+2"
  date_format: "^1.0.4"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:

    - images/loading.jpg


    #四个tab切换图片
    - images/find_normal.png
    - images/find_pressed.png
    - images/contact_list_normal.png
    - images/contact_list_pressed.png
    - images/weixin_normal.png
    - images/weixin_pressed.png
    - images/profile_normal.png
    - images/profile_pressed.png

    #menu
    - images/icon_menu_addfriend.png
    - images/icon_menu_group.png
    - images/icon_menu_scan.png


    - images/icon_addfriend.png
    - images/icon_groupchat.png
    - images/icon_public.png